name: pml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - python=3.12.3
  - tqdm=4.66.4
  - einops=0.8.0
  - pip:
      - neuralprocesses==0.2.5
      - torch==2.3.0
